[workspace]

[package]
name = "solira"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4"
agave-geyser-plugin-interface = "2"
solana-logger = "2"
once_cell = "1"

[dependencies]
tokio.workspace = true
log.workspace = true
agave-geyser-plugin-interface.workspace = true
solana-logger.workspace = true
once_cell.workspace = true
