[workspace]
members = ["geyser-replay", "of1"]

[package]
name = "solira"
version = "0.1.0"
edition = "2021"
authors = ["sam0x17"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4"
agave-geyser-plugin-interface = "2.1.0"
solana-logger = "2.1.0"
solana-program = "2.1.0"
once_cell = "1"
serde_json = "1"

# geyser-replay
reqwest = "0.12"
anyhow = "1"
base64 = "0.22"
bincode = "1.3"
bs58 = "0.5"
cbor = "0.4"
cid = "0.11"
colored = "2.1"
const-hex = "1.12"
crc = "3"
crossbeam-channel = "0.5"
fnv = "1.0"
multihash = "0.19"
prost = { package = "prost", version = "0.13" }
prost_011 = { package = "prost", version = "0.11" }
protobuf-src = "1.1"
serde = "1.0"
serde_cbor = "0.11"
solana-accounts-db = "2.1.5"
solana-entry = "2.1.5"
solana-geyser-plugin-manager = "2.1.5"
solana-rpc = "2.1.5"
solana-runtime = "2.1.5"
solana-sdk = "2.1.5"
solana-storage-proto = "2.1.5"
solana-transaction-status = "2.1.5"
tonic = "0.12"
tonic-build = "0.12"
tracing = "0.1"
zstd = "0.13"
thousands = "0.2"

[dependencies]
tokio.workspace = true
log.workspace = true
agave-geyser-plugin-interface.workspace = true
solana-logger.workspace = true
solana-program.workspace = true
once_cell.workspace = true
serde_json.workspace = true
thousands.workspace = true
