[workspace]

[package]
name = "solira"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4"
agave-geyser-plugin-interface = "2"
solana-logger = "2"
solana-program = "2"
solana-test-validator = "2"
solana-core = "2"
solana-sdk = "2"
solana-geyser-plugin-manager = "2"
solana-rpc = "2"
once_cell = "1"
serde_json = "1"
crossbeam-channel = "0.5"

[dependencies]
tokio.workspace = true
log.workspace = true
agave-geyser-plugin-interface.workspace = true
solana-logger.workspace = true
solana-program.workspace = true
solana-test-validator.workspace = true
solana-core.workspace = true
solana-sdk.workspace = true
solana-geyser-plugin-manager.workspace = true
solana-rpc.workspace = true
once_cell.workspace = true
serde_json.workspace = true
crossbeam-channel.workspace = true
