[workspace]

[package]
name = "solira"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4"
solana-geyser-plugin-interface = "1.18"
solana-logger = "2.0"

[dependencies]
tokio.workspace = true
log.workspace = true
solana-geyser-plugin-interface.workspace = true
solana-logger.workspace = true
