[package]
name = "jetstreamer-build-cdylib"
version = "0.1.0"
edition = "2024"

[lib]
test = false
doc = false

[features]
link-jetstreamer = []
plugin-runner = ["jetstreamer-geyser-plugin/plugin-runner"]

[dependencies]
jetstreamer-geyser-plugin.workspace = true
