[package]
name = "of1"
version = "0.1.0"
edition = "2021"
authors = ["sam0x17"]
license = "MIT"
keywords = ["solana", "old faithful", "CAR", "blockchain", "crypto"]
description = "Allows for direct streaming access to Old Faithful CAR files over HTTP and filecoin"

[dependencies]
