[package]
name = "jetstreamr-build-cdylib"
version = "0.1.0"
edition = "2024"

[lib]
test = false
doc = false

[features]
link-jetstreamr = []

[dependencies]
jetstreamr-geyser-plugin.workspace = true
